# A new Azure Devops project will be created with the following configuration values.
# You can, but don't have to edit these
ado_project_name: "MigrateFromADO"
ado_repository_name: "MigrateFromADORepo"

# Update these values before running the bootstrap script

ado_url: "https://dev.azure.com/stephiereanna2025/"  # e.g "https://dev.azure.com/stephiereanna2025"

